baseURL = "https://EastChord.github.io/" # 1. Your future blog URL
languageCode = "en-us" # 2. Set the language to English
title = "EastChord's Blog" # 3. Your blog's title

theme = "PaperMod"

[params]
  defaultTheme = "auto"
  math = true # 4. Enable KaTeX for math formulas!theme = 'PaperMod'
  showCategorites = true

[menu]
  [[menu.main]]
    identifier = "gametheory"
    name = "Game Theory"
    url = "/gametheory"
    weight = 10